from django.core.management.base import BaseCommand
from members.models import GroundwaterPlace

# The dictionary of English to Hindi names (paste the dictionary here)
place_name_translations = {
    'Alipur': 'अलीपुर',
    'Amin': 'अमीन',
    'Amupur': 'अमूपुर',
    'Anchla': 'अंचला',
    'Andhera': 'अंधेरा',
    'Anjanthali': 'अंजनथली',
    'Ardana': 'अर्दाना',
    'Assandh': 'असंध',
    'Badson': 'बादसन',
    'Bahri': 'बहरी',
    'Balhera-m': 'बलहेड़ा-एम',
    'Balla': 'बल्ला',
    'Balu': 'बालू',
    'Bansa': 'बांसा',
    'Baragaon': 'बरागांव',
    'Barani': 'बरानी',
    'Barthal': 'बर्थल',
    'Bastali': 'बस्तली',
    'Beholpur': 'बहोलपुर',
    'Biana': 'बियाना',
    'Bijna': 'बिजना',
    'Brass': 'ब्रास',
    'Budanpur': 'बुडानपुर',
    'Chakda': 'चकड़ा',
    'Chandsamand': 'चंदसमंद',
    'Chaura': 'चौड़ा',
    'Chirao': 'चिराओ',
    'Chochra': 'चोचरा',
    'Choor': 'चूर',
    'Chorkharsa': 'चोरखरसा',
    'Dabarthala': 'दबारथला',
    'Dachar': 'दचर',
    'Dadupur': 'दादूपुर',
    'Darar': 'दरार',
    'Dhanaura': 'धनौरा',
    'Dhomsi(shallow)': 'धोमसी (शैलो)',
    'Domsi': 'डोंमसी',
    'Faridpur': 'फरीदपुर',
    'Gagsina': 'गगसिना',
    'Gangateri': 'गंगटेरी',
    'Garhi': 'गढ़ी',
    'Gharaunda': 'घारौंदा',
    'Gholpura': 'घोलपुरा',
    'Gogripur': 'गोग्रीपुर',
    'Gohida': 'गोहिदा',
    'Goli': 'गोली',
    'Gondar': 'गोंडार',
    'Gondhar': 'गोंधर',
    'Gudha': 'गुढ़ा',
    'Indri': 'इंद्रि',
    'Islam': 'इस्लाम',
    'Jainpur': 'जैनपुर',
    'Jaisinghpura': 'जैसिंघपुरा',
    'Jalmana': 'जलमना',
    'Janesron': 'जनेसरों',
    'Jani': 'जानी',
    'Jaroli': 'जारोली',
    'Jhanjari': 'झांजरी',
    'Jundla1': 'जुंडला 1',
    'Kachhwa': 'कछवा',
    'Kalampura': 'कलमपुरा',
    'Kalheri': 'कल्हेड़ी',
    'Kalri': 'कलरी',
    'Kalsi': 'कालसी',
    'Kalsora': 'कालसोरा',
    'Kambopura': 'कम्बोपुरा',
    'Khanpur': 'खानपुर',
    'KheriNaru-S': 'खेड़ी नारू-स',
    'Khizrabad': 'खिज़राबाद',
    'Kohnd': 'कोहंड',
    'Kurlan': 'कुर्लन',
    'Kutail': 'कुतैल',
    'Majra': 'माजरा',
    'Makhala': 'माखला',
    'Manak': 'मनक',
    'Manjura': 'मंजुरा',
    'Mehmadpur': 'महमदपुर',
    'Mormazra': 'मोरमजरा',
    'Mound': 'माउंड',
    'Munak': 'मुनक',
    'Mundh-dw': 'मुंढ-डीडब्ल्यू',
    'Mundi': 'मुंडी',
    'Musepur': 'मूसेपुर',
    'Mustafabad': 'मुस्तफाबाद',
    'Nabipur': 'नबीपुर',
    'Nalipur': 'नलीपुर',
    'Nalvi': 'नालवी',
    'Nanhera': 'नन्हेरा',
    'Naru': 'नारू',
    'Nasirpur': 'नसीरपुर',
    'Nilokheri': 'निलोखेड़ी',
    'Nissing': 'निसिंग',
    'Paccakhera-dw': 'पक्काखेरा-डीडब्ल्यू',
    'Padhana-DW': 'पढ़ाना-डीडब्ल्यू',
    'Phurlak': 'फुरलक',
    'Phusgarh': 'फूसगढ़',
    'Popra': 'पोपड़ा',
    'Pundrak': 'पुंदरक',
    'Rambha': 'रामभा',
    'Randauli': 'रंदौली',
    'Ranwar': 'रनवार',
    'Rasin': 'रासिन',
    'Rattak': 'रत्तक',
    'Rindal': 'रिंडल',
    'Risalwa': 'रिसालवा',
    'Sadarpur': 'सदरपुर',
    'Sagga': 'सग्गा',
    'Salwan-B': 'सलवान-बी',
    'Sambli-M': 'संबली-एम',
    'Sambli-S': 'संबली-एस',
    'Samora1': 'समोरा 1',
    'Sekhpura': 'सेखपुरा',
    'Shekhpur': 'शेखपुर',
    'Shekhpura': 'शेखपुरा',
    'Subri': 'सुबरी',
    'Taprana': 'टप्राना',
    'Taraori': 'तारौरी',
    'Udana': 'उदाना',
    'Uplani': 'उपलानी',
    'Newal': 'नेवाल',
    'Jundla(shallow)': 'जुंडला (शैलो)',
    'Karnal': 'करनाल',
    'KheriNaru-D': 'खेड़ी नारू-डी',
    'KheriNaru-M': 'खेड़ी नारू-एम',
    'Islam Nagar': 'इस्लाम नगर',
    'Garhi Khajur': 'गढ़ी खजूर',
    'Chorpur': 'चोर्पुर',
}


class Command(BaseCommand):
    help = 'Update GroundwaterPlace model with Hindi names'

    def handle(self, *args, **kwargs):
        hindi_district = "करनाल"
        places = GroundwaterPlace.objects.all()
        updated_count = 0

        for place in places:
            eng_name = place.name
            if eng_name in place_name_translations:
                place.name_hi = place_name_translations[eng_name]
                place.district_hi = hindi_district
                place.save()
                updated_count += 1
                self.stdout.write(f"Updated: {eng_name} -> {place.name_hi}")

        self.stdout.write(f"Total updated: {updated_count}")
