# Generated by Django 4.2.23 on 2025-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('sample_date', models.DateField()),
            ],
            options={
                'db_table': 'GroundwaterData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterPlace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GroundwaterPlace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='pdf_uploads/')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
