# Generated by Django 4.2.23 on 2025-09-06 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='pdf_uploads/')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterPlace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('district_hi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'GroundwaterPlace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('village', 'Village'), ('town', 'Town')], max_length=20)),
                ('place', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.groundwaterplace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroundwaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('sample_date', models.DateField()),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='members.groundwaterplace')),
            ],
            options={
                'db_table': 'GroundwaterData',
                'managed': True,
            },
        ),
    ]
