# Generated by Django 4.2.23 on 2025-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='groundwaterplace',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='groundwaterpdf',
            table='GroundwaterPDF',
        ),
        migrations.AlterModelTable(
            name='userpreference',
            table='UserPreference',
        ),
    ]
